### ISSUE TITLE
Rewrite Release Checklist

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/paa.gruppe-adler.de#15]
# Browsers
- [x] Chrome
- [x] Firefox
- [x] Opera
- [x] Edge
- [x] Safari

## Things to check
- Adding files via drag-and-drop
- Adding files via button
- [PAA Test Data.zip](https://github.com/gruppe-adler/paa.gruppe-adler.de/files/6563374/PAA.Test.Data.zip) (each file should behave according to its name)
- Look at all Warnings / Errors
- Downloading a single file
- "Download all Files"-Button
- Delete all files
- Delete single file
- "Report Error" button within error / some warning popups
- Feedback popup
- Adding files with same name as existing files (even multiple)
- Offline capabilities

# Pre-Release Checklist
- [x] Fix robots.txt
- [x] Fix `CNAME` input for GitHub action
- [x] Restrict "Deploy" step in GH Actions workflow to `master` branch
- [x] Test all relevant browsers
- [x] Update discord link in feedback popup
- [ ] Merge `rewrite` branch (only after all above are done)
- [ ] Update DNS entries
- [ ] Change "Custom Domain" in GitHub Pages settings

# Post-Release Checklist
- [ ] Tweet
- [ ] Delete Image on Docker Hub
- [ ] Stop docker instance on our server

**Comment by DerZade** [comment]
@nomisum tested Safari Version 13.1.3 (15609.4.1)

Everything seems to be working fine after the fixes we've made.

**Comment by DerZade** [comment]
Edge Version 91.0.864.64

**Comment by DerZade** [comment]
Tested Opera Version 77.0.4054.172 👍

**Comment by DerZade** [comment]
Teste Firefox Version 89.0.2 👍

**Comment by DerZade** [comment]
Tested Chrome Version 91.0.4472.124 👍
